package com.example.pirmaslab.mybatis.model;

public class PlayerTournament {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER_TOURNAMENT.PLAYERS_ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private Long playersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER_TOURNAMENT.TOURNAMENTS_ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private Long tournamentsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER_TOURNAMENT.PLAYERS_ID
     *
     * @return the value of PUBLIC.PLAYER_TOURNAMENT.PLAYERS_ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public Long getPlayersId() {
        return playersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER_TOURNAMENT.PLAYERS_ID
     *
     * @param playersId the value for PUBLIC.PLAYER_TOURNAMENT.PLAYERS_ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setPlayersId(Long playersId) {
        this.playersId = playersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER_TOURNAMENT.TOURNAMENTS_ID
     *
     * @return the value of PUBLIC.PLAYER_TOURNAMENT.TOURNAMENTS_ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public Long getTournamentsId() {
        return tournamentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER_TOURNAMENT.TOURNAMENTS_ID
     *
     * @param tournamentsId the value for PUBLIC.PLAYER_TOURNAMENT.TOURNAMENTS_ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setTournamentsId(Long tournamentsId) {
        this.tournamentsId = tournamentsId;
    }
}