package com.example.pirmaslab.mybatis.model;

import lombok.Getter;

import java.util.List;

public class Player {
    @Getter
    private List<Tournament> tournaments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.EMAIL
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.NAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.SURNAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.USERNAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.ID
     *
     * @return the value of PUBLIC.PLAYER.ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.ID
     *
     * @param id the value for PUBLIC.PLAYER.ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.EMAIL
     *
     * @return the value of PUBLIC.PLAYER.EMAIL
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.EMAIL
     *
     * @param email the value for PUBLIC.PLAYER.EMAIL
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.NAME
     *
     * @return the value of PUBLIC.PLAYER.NAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.NAME
     *
     * @param name the value for PUBLIC.PLAYER.NAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.SURNAME
     *
     * @return the value of PUBLIC.PLAYER.SURNAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.SURNAME
     *
     * @param surname the value for PUBLIC.PLAYER.SURNAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.USERNAME
     *
     * @return the value of PUBLIC.PLAYER.USERNAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.USERNAME
     *
     * @param username the value for PUBLIC.PLAYER.USERNAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setUsername(String username) {
        this.username = username;
    }
}