package com.example.pirmaslab.mybatis.model;

public class Referee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REFEREE.ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REFEREE.EMAIL
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REFEREE.NAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REFEREE.SURNAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REFEREE.ID
     *
     * @return the value of PUBLIC.REFEREE.ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REFEREE.ID
     *
     * @param id the value for PUBLIC.REFEREE.ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REFEREE.EMAIL
     *
     * @return the value of PUBLIC.REFEREE.EMAIL
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REFEREE.EMAIL
     *
     * @param email the value for PUBLIC.REFEREE.EMAIL
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REFEREE.NAME
     *
     * @return the value of PUBLIC.REFEREE.NAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REFEREE.NAME
     *
     * @param name the value for PUBLIC.REFEREE.NAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REFEREE.SURNAME
     *
     * @return the value of PUBLIC.REFEREE.SURNAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REFEREE.SURNAME
     *
     * @param surname the value for PUBLIC.REFEREE.SURNAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
}