package com.example.pirmaslab.mybatis.model;

import java.time.LocalDate;
import java.util.Date;

public class Tournament {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOURNAMENT.ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOURNAMENT.EVENT_START_DATE
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private LocalDate eventStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOURNAMENT.GAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private String game;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOURNAMENT.MAXPLAYERS
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private Integer maxplayers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOURNAMENT.NAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOURNAMENT.REGISTRATION_END_DATE
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private LocalDate registrationEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOURNAMENT.REGISTRATION_START_DATE
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private LocalDate registrationStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOURNAMENT.REFEREE_ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    private Long refereeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOURNAMENT.ID
     *
     * @return the value of PUBLIC.TOURNAMENT.ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOURNAMENT.ID
     *
     * @param id the value for PUBLIC.TOURNAMENT.ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOURNAMENT.EVENT_START_DATE
     *
     * @return the value of PUBLIC.TOURNAMENT.EVENT_START_DATE
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public LocalDate getEventStartDate() {
        return eventStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOURNAMENT.EVENT_START_DATE
     *
     * @param eventStartDate the value for PUBLIC.TOURNAMENT.EVENT_START_DATE
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setEventStartDate(LocalDate eventStartDate) {
        this.eventStartDate = eventStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOURNAMENT.GAME
     *
     * @return the value of PUBLIC.TOURNAMENT.GAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public String getGame() {
        return game;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOURNAMENT.GAME
     *
     * @param game the value for PUBLIC.TOURNAMENT.GAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setGame(String game) {
        this.game = game;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOURNAMENT.MAXPLAYERS
     *
     * @return the value of PUBLIC.TOURNAMENT.MAXPLAYERS
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public Integer getMaxplayers() {
        return maxplayers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOURNAMENT.MAXPLAYERS
     *
     * @param maxplayers the value for PUBLIC.TOURNAMENT.MAXPLAYERS
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setMaxplayers(Integer maxplayers) {
        this.maxplayers = maxplayers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOURNAMENT.NAME
     *
     * @return the value of PUBLIC.TOURNAMENT.NAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOURNAMENT.NAME
     *
     * @param name the value for PUBLIC.TOURNAMENT.NAME
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOURNAMENT.REGISTRATION_END_DATE
     *
     * @return the value of PUBLIC.TOURNAMENT.REGISTRATION_END_DATE
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public LocalDate getRegistrationEndDate() {
        return registrationEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOURNAMENT.REGISTRATION_END_DATE
     *
     * @param registrationEndDate the value for PUBLIC.TOURNAMENT.REGISTRATION_END_DATE
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setRegistrationEndDate(LocalDate registrationEndDate) {
        this.registrationEndDate = registrationEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOURNAMENT.REGISTRATION_START_DATE
     *
     * @return the value of PUBLIC.TOURNAMENT.REGISTRATION_START_DATE
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public LocalDate getRegistrationStartDate() {
        return registrationStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOURNAMENT.REGISTRATION_START_DATE
     *
     * @param registrationStartDate the value for PUBLIC.TOURNAMENT.REGISTRATION_START_DATE
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setRegistrationStartDate(LocalDate registrationStartDate) {
        this.registrationStartDate = registrationStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOURNAMENT.REFEREE_ID
     *
     * @return the value of PUBLIC.TOURNAMENT.REFEREE_ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public Long getRefereeId() {
        return refereeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOURNAMENT.REFEREE_ID
     *
     * @param refereeId the value for PUBLIC.TOURNAMENT.REFEREE_ID
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    public void setRefereeId(Long refereeId) {
        this.refereeId = refereeId;
    }
}