package com.example.pirmaslab.mybatis.dao;

import com.example.pirmaslab.mybatis.model.PlayerTournament;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface PlayerTournamentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER_TOURNAMENT
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    int insert(PlayerTournament record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER_TOURNAMENT
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    List<PlayerTournament> selectAll();

    List<PlayerTournament> selectByPlayer(long playerId);

    PlayerTournament selectByCompositeKey(@Param("player") long playerId, @Param("tournament") long tournamentId);

    void delete(PlayerTournament record);
}