package com.example.pirmaslab.mybatis.dao;

import com.example.pirmaslab.mybatis.model.Referee;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface RefereeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REFEREE
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REFEREE
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    int insert(Referee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REFEREE
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    Referee selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REFEREE
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    List<Referee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REFEREE
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    int updateByPrimaryKey(Referee record);
}