package com.example.pirmaslab.mybatis.dao;

import com.example.pirmaslab.mybatis.model.Tournament;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface TournamentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TOURNAMENT
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TOURNAMENT
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    int insert(Tournament record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TOURNAMENT
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    Tournament selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TOURNAMENT
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    List<Tournament> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TOURNAMENT
     *
     * @mbg.generated Mon Apr 29 12:33:09 EEST 2024
     */
    int updateByPrimaryKey(Tournament record);
}